services:
  db:
    image: postgres:10
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
  web:
    build: ./ipl
    image: ipl:latest
    volumes:
      - ./ipl:/usr/src/app
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: ["gunicorn", "ipl.wsgi:application", "--bind", "0.0.0.0:8080", "--workers", "3"]
    environment:
      - DJANGO_ENV=prod
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    restart: always

